* Introduction

This repo contains emacs lisp code, to add the possibility
to accept email invitations within  notmuch. 

I found this code by a reddit post
- https://www.reddit.com/r/orgmode/comments/5odzem/accept_calendar_invitation_icalics_in_mail

and found the file at
- https://github.com/larkery/emacs-bankruptcy/blob/master/site-lisp/notmuch-calendar-x.el

It was not working out of the box at emacs 27 (at least on my installation), so I changed some 
part of it. Now it works (for me) to capture invitations in an own emacs org file 
(specified by notmuch-calendar-capture-target).

As I am not an expierenced emacs lisper, I don't understand very much of the code, but fortunately 
enough to adjust it for my need. Any help to improve this is welcome. It would be nice, if this might
evolve to a solution for invitations with emacs/notmuch.

** Working parts (tested by day to day use since several months)

- showing the invitatioin and showing the day of the event as an agenda overview
- capture invitations from emails within notmuch

** seems to work, but not extensively tested

- acceptance of invitations (tested with mail provider mailbox.org)
- rejecting an invitation (tested with mail provider mailbox.org)
- sending invitations from an org-mode event by calling notmuch-calendar-send-org-invitation
  with M-x (tested with mail provider mailbox.org)

** possible problems

- timezones were not handled correctly in the beginning, as only the X-WR-TIMEZONE tag of ics is set, 
  I inserted a block of 
  
  #+begin_src
  BEGIN:VTIMEZONE
  TZID:Europe/Berlin
  END:VTIMEZONE
  #+end_src
  with this, the timezone was correctly handled at least by mailbox.org.
  To adjust the timezone, the var org-icalendar-timezone should be set.

- I have not tested repeated appointments (I don't think, they will work)

** not implemented

- tentative replies

