* Introduction

This repo contains emacs lisp code, to add the possibility
to accept email invitations within  notmuch. 

I found this code by a reddit post
- https://www.reddit.com/r/orgmode/comments/5odzem/accept_calendar_invitation_icalics_in_mail

and found the file at
- https://github.com/larkery/emacs-bankruptcy/blob/master/site-lisp/notmuch-calendar-x.el

It was not working out of the box at emacs 27 (at least on my installation), so I changed some 
part of it. Now it works (for me) to capture invitations in an own emacs org file 
(specified by notmuch-calendar-capture-target).

As I am not an expierenced emacs lisper, I don't understand very much of the code, but fortunately 
enough to adjust it for my need. Any help to improve this is welcome. It would be nice, if this might
evolve to a solution for invitations with emacs/notmuch.

* Working parts

The following parts are working as by my observations

- showing the invitatioin and showing the day of the event as an agenda overview
- capture invitations from emails within notmuch
- sending invitations from an org-mode event (by M-x notmuch-calendar-send-org-invitation)


* Not sure if it works

- acceptance of invitations (at the moment an email is opened with the reply, 
  but I have not tested, if this is working correctly, when I send it
  
- rejecting an invitation, newer tried it jet

- tentative for an invitation


